name: monitoring
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  firebase_crashlytics: ^4.3.2
  firebase_dynamic_links: ^6.1.2
  firebase_analytics: ^11.4.2
  firebase_remote_config: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

