name: key_value_storage
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  path_provider: ^2.1.5
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  lints: ^5.0.0
  test: ^1.24.0
