name: fav_qs_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.16.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.9.4
  lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.24.0
