name: component_library
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.25.15

flutter:
  generate: true
  assets:
    - assets/
  fonts:
    - family: Fondamento
      fonts:
        - asset: assets/Fondamento-Regular.ttf
